openapi: 3.0.1
components:
  securitySchemes:
    # See https://demo.identityserver.io/ for configuration details.
    identity_server_auth:
      flows:
        implicit:
          authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          scopes:
            api: "api"
      type: oauth2
info:
  contact:
    email: mpearson@pih.org
  description: "This is a very short api specification"
  license:
    name: Eclipse Public License 1.0
    url: http://opensource.org/licenses/eclipse-1.0.php
  sortOutput: true
  termsOfService: http://swagger.io/terms/
  title: OpenBoxes API specification
  version: "1.0"
paths:
  /test:
    get:
      summary: "Runs a test request against the Identity Server demo API"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
prettyPrint: true
sortOutput: true
security:
  - identity_server_auth:
      - api
servers:
  - url: "https://demo.identityserver.io/api"
    description: "Identity Server test API"
