openapi: 3.0.1
info:
  contact:
    email: mpearson@pih.org
  description: "This is a very short api specification"
  license:
    name: Eclipse Public License 1.0
    url: http://opensource.org/licenses/eclipse-1.0.php
  sortOutput: true
  termsOfService: http://swagger.io/terms/
  title: OpenBoxes API specification
  version: "1.0"
prettyPrint: true
sortOutput: true
